language: node_js
cache:
  directories:
  - node_modules
node_js:
  - '8'
install:
  - npm install
branches:
  only:
    - master
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
